FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["../Ujeby.Blazor.Base/Ujeby.Blazor.Base.csproj", "Ujeby.Blazor.Base/"]
COPY ["WordleGen/WordleGen.csproj", "WordleGen/"]
COPY ["Wordlerererer.App/Wordlerererer.App.csproj", "Wordlerererer.App/"]
RUN dotnet restore "Wordlerererer.App/Wordlerererer.App.csproj"
COPY . .
WORKDIR "/src/Wordlerererer.App"
RUN dotnet build "Wordlerererer.App.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Wordlerererer.App.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf